<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-packages-editor-site-navigation-extended',
	'src' => plugins_url( '/', __FILE__ ) . 'editor-site-navigation-extended{{MIN_SUFFIX}}.js',
	'i18n' => [
		'domain' => 'elementor-pro',
		'replace_requested_file' => false,
	],
	'type' => 'extension',
	'deps' => [
		'elementor-packages-editor-site-navigation',
		'elementor-packages-icons',
	],
];
