<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
add_filter( 'elementor/editor-v2/packages/config', function( $data ) {

	$data['elementor-packages-editor-documents-extended'] = require __DIR__ . '/editor-documents-extended.asset.php';

	$data['elementor-packages-editor-site-navigation-extended'] = require __DIR__ . '/editor-site-navigation-extended.asset.php';
	return $data;
} );
