<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Vite, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-site-navigation-extended',
	'deps' => [
		'elementor-v2-editor-site-navigation',
		'elementor-v2-icons',
	],
];
