<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-editing-panel-extended',
	'deps' => [
		'elementor-v2-editor-controls',
		'elementor-v2-editor-controls-extended',
		'elementor-v2-editor-editing-panel',
		'elementor-v2-editor-props',
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
