<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Vite, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-variables-extended',
	'deps' => [
		'elementor-v2-core-adapter-utils',
		'elementor-v2-editor-controls',
		'elementor-v2-editor-props',
		'elementor-v2-editor-ui',
		'elementor-v2-editor-variables',
		'elementor-v2-icons',
		'elementor-v2-license-api',
		'elementor-v2-schema',
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
