<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-variables-extended',
	'deps' => [
		'elementor-v2-editor-props',
		'elementor-v2-editor-ui',
		'elementor-v2-editor-variables',
		'elementor-v2-icons',
		'elementor-v2-schema',
		'elementor-v2-ui',
		'react',
	],
];
