<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Vite, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-license-api',
	'deps' => [
		'elementor-v2-http-client',
		'elementor-v2-query',
	],
];
