<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-templates-extended',
	'deps' => [
		'elementor-v2-core-adapter-utils',
		'elementor-v2-editor',
		'elementor-v2-editor-documents',
		'elementor-v2-editor-embedded-documents-manager',
		'elementor-v2-editor-global-classes',
		'elementor-v2-editor-styles-repository',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-store',
		'elementor-v2-utils',
		'react',
	],
];
